### ISSUE TITLE
No start branch to clone in the portfolio project

### ISSUE THREAD

**Issue by amodelbello** [angular-in-action/portfolio#2]
Hello there, 
I'm working through the MEAP and there's no starting point for Chapter 6 to checkout. It's just master which is the finished product. I was hoping you could create it.

**Comment by gnomeontherun** [comment]
Thanks for the report, I recently pushed a few changes and removed the `start` tag. It is there now!

**Comment by amodelbello** [comment]
Right on. Thanks for the quick response!
