### ISSUE TITLE
https://angular-in-action-portfolio.firebaseio.com/stocks.json cannot be access

### ISSUE THREAD

**Issue by Chiva-Zhao** [angular-in-action/portfolio#3]
When I run `ng start` and open localhost:4200, the right `All Stocks` panel no data show up.
I open the Chrome debug console report:
`angular-in-action-portfolio.firebaseio.com/stocks.json:
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT`

I think the URL:https://angular-in-action-portfolio.firebaseio.com/stocks.json is broken.

**Comment by gnomeontherun** [comment]
I just loaded it and it gave me data, can you double check?

**Comment by flutist** [comment]
I also can not get data from the api upl

**Comment by gnomeontherun** [comment]
I also was able to load it, are you sure you have the URL right?
